name: Launch script
on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

jobs:
  launch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run scrapper and push
        run: |
          tar -xzf scrapper.tar.gz
          ./scrapper settings.json
          ./wordcount settings.json
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add data
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
