name: Launch script
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '*/10 * * * *'

jobs:
  launch:
    runs-on: ubuntu-latest
    steps:
      - name: Download last bin
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "renato145/gh_actions_explore"
          version: "latest"
          file: "scrapper"
      - name: Run scrapper
        run: |
          chmod +x scrapper
          ./scrapper
