name: Launch script
on:
  workflow_dispatch:
  # schedule:
  #   - cron: '*/10 * * * *'

jobs:
  launch:
    runs-on: ubuntu-latest
    steps:
      - uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: "dsaltares/godot-wild-jam-18"
          version: "latest"
          file: "plague-linux.zip"
          token: ${{ secrets.YOUR_TOKEN }}
      # - name: Download binary
      #   uses: actions/download-artifact@v2
      #   with:
      #     name: bin-scrapper
      # - name: Run scrapper
      #   run: |
      #     chmod +x scrapper
      #     ./scrapper
