name: Launch script
on:
  workflow_dispatch:
  # schedule:
    # - cron: '*/10 * * * *'

jobs:
  launch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download last bin
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: ${{ github.repository }}
          version: "latest"
          file: "scrapper"
      - name: Run scrapper and push
        run: |
          sudo chown $USER:$GROUP scrapper
          chmod +x scrapper
          ./scrapper settings.json
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          timestamp=$(date -u)
          git commit -m "Latest data: ${timestamp}" || exit 0
          git push
