name: launch
on:
  workflow_dispatch:

jobs:
  launch:
    runs-on: ubuntu-latest
    steps:
      - name: Download binary
        uses: actions/download-artifact@v2
        with:
          name: bin-scrapper
      - name: Run scrapper
        run: scrapper