name: Build and release
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'news_scrapper/**'

jobs:
  debug:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch'
    steps:
      - name: see payload
        run: echo "$PAYLOAD"
        env:
          PAYLOAD: ${{ toJSON(github.event) }}

  build:
    runs-on: ubuntu-latest
    if: github.event_name != 'schedule'
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build binary
        run: |
          cd news_scrapper
          cargo build --release --all-features
          cd ..
          mv news_scrapper/target/release/news_scrapper scrapper
          tar -czf scrapper.tar.gz scrapper
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add scrapper.tar.gz
          timestamp=$(date -u)
          git commit -m "Latest bin build: ${timestamp}" || exit 0
          git push
