name: Build and launch scrapper
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'news_scrapper'
  schedule:
    - cron: '*/10 * * * *'

jobs:
  debug:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch'
    steps:
      - name: see payload
        run: echo "$PAYLOAD"

  build:
    runs-on: ubuntu-latest
    if: github.event_name != 'schedule'
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build binary
        run: |
          cd news_scrapper
          cargo build --release --all-features
          mv target/release/news_scrapper ../scrapper
      - uses: actions/upload-artifact@v2
        with:
          name: bin-scrapper
          path: scrapper

  launch:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download binary
        uses: actions/download-artifact@v2
        with:
          name: bin-scrapper
      - name: Run scrapper
        run: |
          chmod +x scrapper
          ./scrapper
