name: Build and release
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'news_scrapper/**'

jobs:
  debug:
    runs-on: ubuntu-latest
    if: github.event_name != 'workflow_dispatch'
    steps:
      - name: see payload
        run: echo "$PAYLOAD"
        env:
          PAYLOAD: ${{ toJSON(github.event) }}

  build:
    runs-on: ubuntu-latest
    if: github.event_name != 'schedule'
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: Build binary
        run: |
          cd news_scrapper
          cargo build --release --all-features
          mv target/release/news_scrapper scrapper

      - id: fetch-latest-release
        uses: thebritican/fetch-latest-release@v2.0.0

      - name: Upload Binary Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.fetch-latest-release.outputs.upload_url }}
          asset_path: ./news_scrapper/scrapper
          asset_name: scrapper
          asset_content_type: application/octet-stream
