name: load_news
on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - '*.md'
      - '.git*'
jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
      - name: see payload
        run: echo "$PAYLOAD"

  launch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: |
        cd news_scrapper
        cargo build --release --all-features
        mv news_scrapper/target/release/news_scrapper ../news_scrapper
        cd ..
        news_scrapper
